### PR TITLE
Model sizes included in dict

### PR DESCRIPTION
**Pull request by jakethekoenig**
Importantly vision model added. Less importantly legacy models have their context size explicitly given.

### CODE REVIEW

**Comment by jakethekoenig** [comment]
I guess this also fixes a bug in the gpt-3.5 context sizes which were listed as 4097 but are actually 4096. I listed the models in the same order as this [doc](https://platform.openai.com/docs/models/gpt-3-5)

**Comment by PCSwingle** [comment]
Thanks so much for doing this! Do you think you could also do the same for the function below this one (the price function)?

**Comment by jakethekoenig** [comment]
Legacy gpt-3.5 prices aren't listed so I'm not 100% sure they're right. But there's no reason to use them anymore so it seems fine if they're slightly off.

**Review by PCSwingle — APPROVED** [review]
Thanks for doing this! Ideally there would be some way for us to fetch the context length and price from openai's api, but we can this is great.

**Pull request merged**
