### PR TITLE
Redo undo printing

### LINKED ISSUE #356: /undo /redo print changes
We should show the actual changes that happen with the user /undo or /redo's

### PR DESCRIPTION
**Pull request by PCSwingle**
Fixes #356.

### CODE REVIEW

**Review by biobootloader — APPROVED** [review]
nice 👍

**Comment by biobootloader** [comment]
actually should we display the inverse of the changes? I'm not sure what would be clearer...

**Comment by biobootloader** [comment]
Like here the undo changes would be red - lines: image

**Comment by PCSwingle** [comment]
I think it makes sense the way it currently is, but I definitely see both sides.

**Comment by granawkins** [comment]
I too think red makes sense. Maybe a simple 'inverse' arg somewhere could make this simple.

**Comment by biobootloader** [comment]
Maybe we could keep the edit the same but surround it with something to make it more clear it's being undone? Or indent the whole block with some prefix for all the lines to show it's an undo?

**Comment by PCSwingle** [comment]
> Maybe we could keep the edit the same but surround it with something to make it more clear it's being undone? Or indent the whole block with some prefix for all the lines to show it's an undo?

I prefer this approach a lot; what are your thoughts for how we would make it clearer though?

**Comment by biobootloader** [comment]
Thoughts?

```
>>> add exp
Total token count: 1448
Streaming... use control-c to interrupt the model at any point

I will add a new function to handle exponentiation and update the calculate function to include this new operation.
Steps:
1. Add a new function `exponentiate_numbers` to perform exponentiation.
2. Update the `calculate` function to handle the "exponentiate" operation.

testbed/scripts/calculator.py
============================================================
15:
16:def divide_numbers(a, b):
+  def exponentiate_numbers(a, b):
+      return a ** b
17:    return a / b
18:
============================================================
29:    elif operation == "divide":
30:        result = divide_numbers(num1, num2)
+      elif operation == "exponentiate":
+          result = exponentiate_numbers(num1, num2)
31:    else:
32:        print("Invalid operation")
============================================================
Speed: 22.01 tkns/s | Cost: $0.02
Apply these changes? 'Y/n/i' or provide feedback.
>>>
Changes applied.

What can I do for you?
>>> /undo

UNDO: testbed/scripts/calculator.py
UNDO: ============================================================
UNDO: 29:    elif operation == "divide":
UNDO: 30:        result = divide_numbers(num1, num2)
UNDO: +      elif operation == "exponentiate":
UNDO: +          result = exponentiate_numbers(num1, num2)
UNDO: 31:    else:
UNDO: 32:        print("Invalid operation")
UNDO: ============================================================

UNDO: testbed/scripts/calculator.py
UNDO: ============================================================
UNDO: 15:
UNDO: 16:def divide_numbers(a, b):
UNDO: +  def exponentiate_numbers(a, b):
UNDO: +      return a ** b
UNDO: 17:    return a / b
UNDO: 18:
UNDO: ============================================================
Edits to file /Users/biobootloader/code/mentat/testbed/scripts/calculator.py undone
Undo complete
```

**Comment by PCSwingle** [comment]
Oh, I like this a lot! I'll get this done and then merge.

**Pull request merged**
